### ISSUE TITLE
GFW List有问题怎么可能才300条现在看隔壁因该是有37万条左右的

### ISSUE THREAD

**Issue by hayashi-mami** [wbcyclist/merlin_shadowsocks#1]
https://github.com/gfwlist/gfwlist
要是直接可以套用隔壁base64压缩过的列表就好了
可以节省列表空间 也免得单独维护列表

**Comment by wbcyclist** [comment]
这个是我自用的ss，gfwlist里只加我常用的站点，没必要加载根本用不上的37W条规则。
如果你想要全规则的gfwlist，你可以去 https://github.com/hq450/fancyss 原repo下载
或者你想自定义自己的gfwlist规则，可以用这个https://github.com/wbcyclist/my_gfw_list 维护规则后将生成的gfwlist.conf替换到maintain_files文件夹下，再执行build.sh，打包后，shadowsocks.tar.gz里的gfwlist就是你自己的规则了。
