### ISSUE TITLE
订阅问题

### ISSUE THREAD

**Issue by w0330t** [wbcyclist/merlin_shadowsocks#3]
我打开订阅然后给我提示这个
【2018年10月19日 19:16:24】: 订阅功能不支持X7.7以下的固件，当前固件版本7.9.1，请更新固件！

**Comment by aufwies** [comment]
我也同样遇到了这个问题。请求帮忙fix

**Comment by wbcyclist** [comment]
已修复

**Comment by ekkoun** [comment]
订阅功能不支持X7.7以下的固件，当前固件版本7.9.1，请更新固件！
![image](https://user-images.githubusercontent.com/28840419/71637999-8f565780-2c8e-11ea-9515-1165a23ffffb.png)
shadowsocks_4.2.1版本
