### ISSUE TITLE
4.1.4一些明显需要走代理的网站（如pornhub）用gfwlist模式无效，添加到黑名单强制走代理也无效，全局模式却可以上。

### ISSUE THREAD

**Issue by woyebuzhidaoa** [wbcyclist/merlin_shadowsocks#4]
4.1.4版本，一些明显需要走代理的网站（如pornhub）用gfwlist模式无效，添加到黑名单强制走代理也无效，全局模式却可以上。各种DNS模式都尝试过。不理解为何全局能上，但添加到黑名单强制走代理无效。

**Comment by w0330t** [comment]
> 4.1.4版本，一些明显需要走代理的网站（如pornhub）用gfwlist模式无效，添加到黑名单强制走代理也无效，全局模式却可以上。各种DNS模式都尝试过。不理解为何全局能上，但添加到黑名单强制走代理无效。

gfwlist列表好像是不是完整版的而是作者自用的精简版，需要自己加黑名单。

**Comment by wbcyclist** [comment]
已将pornhub加入gfwlist ![doge](https://user-images.githubusercontent.com/2424522/49133674-d94a6c80-f31b-11e8-8481-851b566af920.jpg)
